// datos/productos.js
export const PRODUCTOS = [
  {
    id: '1', nombre: 'Base Fluida Cobertura Total', marca: 'GlowLab',
    precio: 62000, categoria: 'Maquillaje', tipo: 'Base',
    funcion: 'Cobertura total de larga duración. Acabado semimate y natural.',
    tipoPiel: ['Normal', 'Grasa', 'Mixta'],
    tonos: [
      { nombre: 'Ivory',      hex: '#F5E6D3' },
      { nombre: 'Sand',       hex: '#D4A574' },
      { nombre: 'Caramel',    hex: '#B8864E' },
      { nombre: 'Espresso',   hex: '#6B3A2A' },
    ],
    ingredientesDestacados: ['Niacinamida', 'Vitamina C', 'SPF 15'],
    spf: 15,
    imagen: require('../assets/productos/base-fluida.png'),
  },
  {
    id: '2', nombre: 'Labial Líquido Mate 12h', marca: 'GlowLab',
    precio: 35000, categoria: 'Maquillaje', tipo: 'Labios',
    funcion: 'Color intenso y mate de hasta 12 horas sin resecar.',
    tipoPiel: ['Normal', 'Grasa', 'Mixta', 'Seca'],
    tonos: [
      { nombre: 'Nude Rose',  hex: '#C8907A' },
      { nombre: 'Berry',      hex: '#8B2252' },
      { nombre: 'Coral',      hex: '#E8735A' },
    ],
    ingredientesDestacados: ['Vitamina E', 'Aceite de jojoba'],
    spf: null,
    imagen: require('../assets/productos/labial-mate.png'),
  },
  {
    id: '3', nombre: 'Serum Vitamina C Iluminador', marca: 'GlowSkin',
    precio: 89000, categoria: 'Skincare', tipo: 'Serum',
    funcion: 'Unifica el tono, reduce manchas y da luminosidad en 4 semanas.',
    tipoPiel: ['Normal', 'Seca', 'Mixta'],
    tonos: [],  // los serums no tienen tonos
    ingredientesDestacados: ['Vitamina C 15%', 'Ácido hialurónico', 'Niacinamida'],
    spf: null,
    imagen: require('../assets/productos/serum-vitamina-c.png'),
  },
  {
    id: '4', nombre: 'Hidratante FPS 50+ Piel Grasa', marca: 'GlowSkin',
    precio: 75000, categoria: 'Bloqueador', tipo: 'Bloqueador',
    funcion: 'Protección solar de amplio espectro. Textura gel-fluido, sin brillos.',
    tipoPiel: ['Grasa', 'Mixta'],
    tonos: [],
    ingredientesDestacados: ['Filtro UV mineral', 'Zinc', 'Niacinamida'],
    spf: 50,
    imagen: require('../assets/productos/bloqueador-grasa.png'),
  },
  {
    id: '5', nombre: 'Paleta de Sombras Nude', marca: 'GlowLab',
    precio: 95000, categoria: 'Maquillaje', tipo: 'Ojos',
    funcion: '12 tonos neutros y marrones para looks de día y noche.',
    tipoPiel: ['Normal', 'Grasa', 'Mixta', 'Seca', 'Sensible'],
    tonos: [
      { nombre: 'Champagne', hex: '#F7E7CE' },
      { nombre: 'Taupe',     hex: '#8B7355' },
      { nombre: 'Cocoa',     hex: '#6B4226' },
    ],
    ingredientesDestacados: ['Talco', 'Mica', 'Vitamina E'],
    spf: null,
    imagen: require('../assets/productos/paleta-nude.png'),
  },
  {
    id: '6', nombre: 'Limpiador Facial Espuma', marca: 'GlowSkin',
    precio: 42000, categoria: 'Skincare', tipo: 'Limpiador',
    funcion: 'Limpieza profunda sin resecar. Remueve maquillaje y exceso de grasa.',
    tipoPiel: ['Grasa', 'Mixta', 'Normal'],
    tonos: [],
    ingredientesDestacados: ['Ácido salicílico', 'Aloe vera', 'Té verde'],
    spf: null,
    imagen: require('../assets/productos/limpiador-espuma.png'),
  },
]
